Algoritmo "medidas"






Var

  Quadrado, Triangulo, Trapezio, A , B, C: real



Inicio

escreva("Digite a medida A: ")
leia(A)
escreva("Digite a medida B: ")
leia(B)
escreva("Digite a medida C: ")
leia(C)

 Quadrado <- exp(A,2)
 
 Triangulo <- A * B / 2
 
 Trapezio <-   ( A + B ) * C / 2

escreval(" AREA DO QUADRADO = ", quadrado:6:4 )
escreval(" AREA DO TRIANGULO = ", triangulo:6:4 )

escreval(" AREA DO TRAPEZIO = ", trapezio:6:4 )



Fimalgoritmo